[project]
name = "atmoflux"
dynamic = ["version"]
description = "Atmospheric and energy flux analysis library by Telluris Labs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.22"
]
authors = [
    { name = "Telluris Labs", email = "info@tellurislabs.io" }
]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["atmospheric science","climate science","micrometeorology","surface energy balance","land-atmosphere exchange",
    "energy fluxes", "radiative fluxes","turbulent fluxes","hydrological fluxes","boundary layer","urban climate"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Hydrology"   
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://tellurislabs.io"
Source = "https://github.com/Telluris-Labs/atmoflux"
"Bug Tracker" = "https://github.com/Telluris-Labs/atmoflux/issues"

[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["atmoflux*"]
exclude = ["tests*"]

[tool.setuptools.dynamic]
version = {attr = "atmoflux.__version__"}
